"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var product_1 = require("../ex1/product");
var customer_1 = require("../ex3/customer");
var transaction_1 = require("./transaction");
var egg = new product_1.Product('Egg', 6, 'Diary');
var pen = new product_1.Product('Pen', 10, 'Stationary');
var book = new product_1.Product('Book A', 40, 'Book');
var notebook = new product_1.Product('Note', 50, 'Stationary');
var apple = new product_1.Product('Apple', 30, 'Fruit');
var customer1 = new customer_1.Customer('Anu', 'anu1234@gmail.com');
var customer2 = new customer_1.Customer('Carlyn', 'carlyndawnjacintha@gmail.com');
customer1.addPurchasedProduct(apple);
customer1.addPurchasedProduct(egg);
customer1.addPurchasedProduct(pen);
customer2.addPurchasedProduct(pen);
customer2.addPurchasedProduct(book);
customer2.addPurchasedProduct(notebook);
customer1.listCustomerPurchase();
transaction_1.Transaction.calculateTotal(customer1.purchasedProduct);
customer2.listCustomerPurchase();
transaction_1.Transaction.calculateTotal(customer2.purchasedProduct);
