"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var product_1 = require("../ex1/product");
var inventory_1 = require("./inventory");
var egg = new product_1.Product('Egg', 6, 'Diary');
var pen = new product_1.Product('Pen', 10, 'Stationary');
var book = new product_1.Product('Book A', 40, 'Book');
var notebook = new product_1.Product('Note', 50, 'Stationary');
var apple = new product_1.Product('Apple', 30, 'Fruit');
var itemegg = new inventory_1.Inventory.InventoryItem(egg, 50);
var itempen = new inventory_1.Inventory.InventoryItem(pen, 10);
var itembook = new inventory_1.Inventory.InventoryItem(book, 20);
var itemnotebook = new inventory_1.Inventory.InventoryItem(notebook, 30);
var itemapple = new inventory_1.Inventory.InventoryItem(apple, 30);
console.log('Before Restocking');
inventory_1.Inventory.InventoryItem.checkStock(itemegg);
inventory_1.Inventory.InventoryItem.checkStock(itempen);
inventory_1.Inventory.InventoryItem.checkStock(itemnotebook);
inventory_1.Inventory.InventoryItem.addStock(itemegg, 5);
inventory_1.Inventory.InventoryItem.addStock(itempen, 10);
inventory_1.Inventory.InventoryItem.addStock(itemnotebook, 5);
console.log('\nAfter Restocking');
inventory_1.Inventory.InventoryItem.checkStock(itemegg);
inventory_1.Inventory.InventoryItem.checkStock(itempen);
inventory_1.Inventory.InventoryItem.checkStock(itemnotebook);
