"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var customer_1 = require("./customer");
var product_1 = require("../ex1/product");
var orange = new product_1.Product('Orange', 50, 'Fruit');
var pen = new product_1.Product('Pen', 10, 'Stationary');
var egg = new product_1.Product('Egg', 6, 'Diary');
var book = new product_1.Product('Book A', 40, 'Book');
var notebook = new product_1.Product('Note', 40, 'Stationary');
var customer1 = new customer_1.Customer('Anu', 'anu1234@gmail.com');
var customer2 = new customer_1.Customer('Carlyn', 'carlyndawnjacintha@gmail.com');
customer1.addPurchasedProduct(orange);
customer1.addPurchasedProduct(egg);
customer1.addPurchasedProduct(pen);
customer2.addPurchasedProduct(pen);
customer2.addPurchasedProduct(book);
customer2.addPurchasedProduct(notebook);
customer1.listCustomerPurchase();
customer2.listCustomerPurchase();
